### ISSUE TITLE
A question regarding the lr scheduler

### ISSUE THREAD

**Issue by viyjy** [mosaicml/diffusion#27]
Hi, is that correct to set milestones to 200ep? Thanks.
```
milestones:
    - 200ep
```
https://github.com/mosaicml/diffusion/blob/2eb6228ef205832aaf7d3111b64a38cdfa4c06f6/yamls/hydra-yamls/SD-2-base-256.yaml#LL62C14-L62C14

**Comment by Landanjs** [comment]
Hi, this is a hold over from a previous experiment. For our training LR schedule, we used linear warmup then a constant learning rate. As long as your number of epochs is < 200, the config you posted will work.

Below is an alternative more accurate config:

```
scheduler:
  _target_: composer.optim.LinearWithWarmupScheduler
  t_warmup: 10000ba
  alpha_i: 1.0
  alpha_f: 1.0
```
